### ISSUE TITLE
Error on Reaching Main Menu

### ISSUE THREAD

**Issue by NV-6155** [GTFO-Modding/MTFO#41]
Game starts up, shows the "MODDED" watermark in the bottom right. Once it gets to the main menu, no rundowns are displayed.

Clean install. Only things installed are latest versions of BepInEx and MTFO, both through R2modman. The same error throws each time the "RUNDOWNS" button in the top left of the menu is clicked.

[LogOutput.log](https://github.com/GTFO-Modding/MTFO/files/13625592/LogOutput.log)

**Comment by Kasuromi** [comment]
Fixed by #40, this fix will be present in the next package bump.
